package main

import (
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"time"
)

const maxCommandRunes = 4000

type Server struct{core *Core;store *Store;tools *ToolRegistry;model ModelAdapter;allowedOrigin string;recovery RecoveryReport;tasks *TaskRunner;improvements *ImprovementManager}
func writeJSON(w http.ResponseWriter,status int,v any){w.Header().Set("Content-Type","application/json");w.WriteHeader(status);_=json.NewEncoder(w).Encode(v)}
func decodeJSON(w http.ResponseWriter,r *http.Request,dst any)error{r.Body=http.MaxBytesReader(w,r.Body,64*1024);dec:=json.NewDecoder(r.Body);dec.DisallowUnknownFields();if err:=dec.Decode(dst);err!=nil{return err};var extra any;err:=dec.Decode(&extra);if errors.Is(err,io.EOF){return nil};if err==nil{return errors.New("multiple json values")};return fmt.Errorf("trailing json rejected: %w",err)}
func normalizedCommand(goal,message string)(string,error){v:=strings.TrimSpace(goal);if v==""{v=strings.TrimSpace(message)};if v==""{return "",errors.New("goal is required")};if len([]rune(v))>maxCommandRunes{return "",fmt.Errorf("goal exceeds %d characters",maxCommandRunes)};return v,nil}
func(s *Server)middleware(next http.Handler)http.Handler{return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){
	if !loopbackRemote(r.RemoteAddr){writeJSON(w,http.StatusForbidden,map[string]string{"error":"loopback only"});return}
	origin:=r.Header.Get("Origin");if origin!=""{if origin!=s.allowedOrigin&&origin!="http://localhost:8000"&&origin!="http://127.0.0.1:8000"{writeJSON(w,http.StatusForbidden,map[string]string{"error":"origin denied"});return};w.Header().Set("Access-Control-Allow-Origin",origin);w.Header().Set("Vary","Origin");w.Header().Set("Access-Control-Allow-Private-Network","true")}
	w.Header().Set("Access-Control-Allow-Headers","Content-Type");w.Header().Set("Access-Control-Allow-Methods","GET,POST,OPTIONS");w.Header().Set("X-Content-Type-Options","nosniff");w.Header().Set("Cache-Control","no-store")
	if r.Method==http.MethodOptions{w.WriteHeader(http.StatusNoContent);return};next.ServeHTTP(w,r)
})}
func(s *Server)routes()http.Handler{mux:=http.NewServeMux()
	mux.HandleFunc("GET /",serveUI)
	mux.HandleFunc("GET /health",func(w http.ResponseWriter,r *http.Request){m,rc:=s.store.Counts();writeJSON(w,200,map[string]any{"ok":true,"version":version,"time":time.Now().UTC(),"model_configured":s.model.Available(),"embedding_configured":s.core.embedding!=nil,"memory_count":m,"receipt_count":rc})})
	mux.HandleFunc("GET /status",func(w http.ResponseWriter,r *http.Request){m,rc:=s.store.Counts();writeJSON(w,200,map[string]any{"version":version,"core":"online","model":map[bool]string{true:"available",false:"not_configured"}[s.model.Available()],"memory_count":m,"receipt_count":rc,"workspace":s.tools.workspace,"windows_computer_use":"observe_only_rc1","stable_candidate_policy":"candidate_only_no_auto_promotion","candidate":"candidate/c9-53-memory-retrieval-rebuild","stable":"unchanged","security":map[string]any{"loopback_only":true,"origin_allowlist":true,"shell_execution":false,"tool_allowlist":true,"capability_gate":true,"signed_passports":true,"passport_max_ttl_seconds":int(maxPassportTTL/time.Second),"mutating_tools":map[bool]int{true:6,false:5}[runtime.GOOS=="windows"],"destructive_tools":1,"recoverable_delete":true,"max_body_bytes":64*1024,"max_command_characters":maxCommandRunes}})})
	mux.HandleFunc("POST /command",func(w http.ResponseWriter,r *http.Request){var req struct{Goal string `json:"goal"`;Message string `json:"message"`};if err:=decodeJSON(w,r,&req);err!=nil{writeJSON(w,400,map[string]string{"error":err.Error()});return};goal,err:=normalizedCommand(req.Goal,req.Message);if err!=nil{writeJSON(w,400,map[string]string{"error":err.Error()});return};ctx,cancel:=context.WithTimeout(r.Context(),65*time.Second);defer cancel();res:=s.core.Execute(ctx,goal);code:=200;if res.Status=="blocked"{code=400}else if res.Status=="error"{code=500}else if res.Status=="unavailable"{code=503};writeJSON(w,code,res)})
	mux.HandleFunc("GET /memory",func(w http.ResponseWriter,r *http.Request){q:=r.URL.Query().Get("q");n,_:=strconv.Atoi(r.URL.Query().Get("limit"));writeJSON(w,200,map[string]any{"items":s.store.SearchMemoryHybrid(r.Context(),q,n,s.core.embedding)})})
	mux.HandleFunc("POST /memory",func(w http.ResponseWriter,r *http.Request){var req struct{Text string `json:"text"`;Type string `json:"type"`;Provenance string `json:"provenance"`;ValidUntil *time.Time `json:"valid_until"`;Supersedes string `json:"supersedes"`};if err:=decodeJSON(w,r,&req);err!=nil{writeJSON(w,400,map[string]string{"error":err.Error()});return};if strings.TrimSpace(req.Type)==""{req.Type="fact"};if strings.TrimSpace(req.Provenance)==""{req.Provenance="http-local"};m,created,err:=s.store.SaveGovernedMemory(r.Context(),req.Text,MemoryWriteMeta{Type:req.Type,Provenance:req.Provenance,ValidUntil:req.ValidUntil,Supersedes:req.Supersedes},s.core.embedding);if err!=nil{writeJSON(w,400,map[string]string{"error":err.Error()});return};writeJSON(w,200,map[string]any{"memory":m,"created":created})})
	mux.HandleFunc("GET /receipts",func(w http.ResponseWriter,r *http.Request){n,_:=strconv.Atoi(r.URL.Query().Get("limit"));writeJSON(w,200,map[string]any{"items":s.store.RecentReceipts(n)})})
	mux.HandleFunc("GET /flight",func(w http.ResponseWriter,r *http.Request){if s.core.recorder==nil{writeJSON(w,http.StatusServiceUnavailable,map[string]string{"error":"flight recorder unavailable"});return};n,_:=strconv.Atoi(r.URL.Query().Get("limit"));items,err:=s.core.recorder.Recent(n);if err!=nil{writeJSON(w,500,map[string]string{"error":err.Error()});return};writeJSON(w,200,map[string]any{"items":items})})
	mux.HandleFunc("GET /tools",func(w http.ResponseWriter,r *http.Request){writeJSON(w,200,map[string]any{"tools":s.tools.List(),"mutating_tools":[]string{"fs.write.workspace","fs.mkdir.workspace","fs.move.workspace","fs.delete.workspace","fs.restore.workspace"},"destructive_tools":[]string{"fs.delete.workspace"},"delete_mode":"quarantine_recoverable"})})
	mux.HandleFunc("GET /capabilities",func(w http.ResponseWriter,r *http.Request){writeJSON(w,200,map[string]any{"gate":"active","passport":"hmac-sha256","max_ttl_seconds":int(maxPassportTTL/time.Second),"tool_capabilities":capabilityCatalog()})})
	mux.HandleFunc("GET /recovery/status",func(w http.ResponseWriter,r *http.Request){writeJSON(w,200,s.recovery)})
	mux.HandleFunc("GET /resources",func(w http.ResponseWriter,r *http.Request){writeJSON(w,200,map[string]any{"runtime":CaptureResources(),"model":s.model.RuntimeProfile(),"measurement_scope":"this NEURA process on this machine"})})
	mux.HandleFunc("POST /tasks",func(w http.ResponseWriter,r *http.Request){if s.tasks==nil{writeJSON(w,503,map[string]string{"error":"task runner unavailable"});return};var req struct{ID string `json:"id"`;Goal string `json:"goal"`;Plan Plan `json:"plan"`};if err:=decodeJSON(w,r,&req);err!=nil{writeJSON(w,400,map[string]string{"error":err.Error()});return};task,err:=s.tasks.store.Create(req.ID,req.Goal,req.Plan,s.tools.List());if err!=nil{writeJSON(w,400,map[string]string{"error":err.Error()});return};writeJSON(w,201,task)})
	mux.HandleFunc("GET /tasks",func(w http.ResponseWriter,r *http.Request){if s.tasks==nil{writeJSON(w,503,map[string]string{"error":"task runner unavailable"});return};n,_:=strconv.Atoi(r.URL.Query().Get("limit"));writeJSON(w,200,map[string]any{"items":s.tasks.store.List(n)})})
	mux.HandleFunc("GET /tasks/{id}",func(w http.ResponseWriter,r *http.Request){if s.tasks==nil{writeJSON(w,503,map[string]string{"error":"task runner unavailable"});return};task,ok:=s.tasks.store.Get(r.PathValue("id"));if !ok{writeJSON(w,404,map[string]string{"error":"task not found"});return};writeJSON(w,200,task)})
	mux.HandleFunc("POST /tasks/{id}/next",func(w http.ResponseWriter,r *http.Request){if s.tasks==nil{writeJSON(w,503,map[string]string{"error":"task runner unavailable"});return};var req struct{Generation uint64 `json:"generation"`};if err:=decodeJSON(w,r,&req);err!=nil{writeJSON(w,400,map[string]string{"error":err.Error()});return};ctx,cancel:=context.WithTimeout(r.Context(),65*time.Second);defer cancel();task,res,err:=s.tasks.RunNext(ctx,r.PathValue("id"),req.Generation);if err!=nil{writeJSON(w,409,map[string]string{"error":err.Error()});return};writeJSON(w,200,map[string]any{"task":task,"result":res})})
	mux.HandleFunc("POST /tasks/{id}/resolve",func(w http.ResponseWriter,r *http.Request){if s.tasks==nil{writeJSON(w,503,map[string]string{"error":"task runner unavailable"});return};var req struct{Generation uint64 `json:"generation"`;EffectVerified bool `json:"effect_verified"`};if err:=decodeJSON(w,r,&req);err!=nil{writeJSON(w,400,map[string]string{"error":err.Error()});return};task,err:=s.tasks.store.ResolveManualReview(r.PathValue("id"),req.Generation,req.EffectVerified);if err!=nil{writeJSON(w,409,map[string]string{"error":err.Error()});return};writeJSON(w,200,task)})
	mux.HandleFunc("POST /tasks/{id}/retry",func(w http.ResponseWriter,r *http.Request){if s.tasks==nil{writeJSON(w,503,map[string]string{"error":"task runner unavailable"});return};var req struct{Generation uint64 `json:"generation"`};if err:=decodeJSON(w,r,&req);err!=nil{writeJSON(w,400,map[string]string{"error":err.Error()});return};task,err:=s.tasks.store.RetryBlocked(r.PathValue("id"),req.Generation);if err!=nil{writeJSON(w,409,map[string]string{"error":err.Error()});return};writeJSON(w,200,task)})
	mux.HandleFunc("POST /improvements",func(w http.ResponseWriter,r *http.Request){if s.improvements==nil{writeJSON(w,503,map[string]string{"error":"improvement manager unavailable"});return};var req struct{ID string `json:"id"`;MacroArea string `json:"macro_area"`;Changes []ImprovementChange `json:"changes"`};if err:=decodeJSON(w,r,&req);err!=nil{writeJSON(w,400,map[string]string{"error":err.Error()});return};c,err:=s.improvements.Stage(req.ID,req.MacroArea,req.Changes);if err!=nil{writeJSON(w,400,map[string]string{"error":err.Error()});return};writeJSON(w,201,c)})
	mux.HandleFunc("GET /improvements/{id}",func(w http.ResponseWriter,r *http.Request){if s.improvements==nil{writeJSON(w,503,map[string]string{"error":"improvement manager unavailable"});return};c,err:=s.improvements.Get(r.PathValue("id"));if errors.Is(err,os.ErrNotExist){writeJSON(w,404,map[string]string{"error":"candidate not found"});return};if err!=nil{writeJSON(w,500,map[string]string{"error":err.Error()});return};writeJSON(w,200,c)})
	mux.HandleFunc("GET /windows/status",func(w http.ResponseWriter,r *http.Request){writeJSON(w,200,map[string]any{"available":runtime.GOOS=="windows","observe":map[bool]string{true:"available",false:"not_on_windows"}[runtime.GOOS=="windows"],"understand":"deterministic_v1","preflight":"fixed_app_allowlist_and_signed_capability","action":"allowlisted_launch_v1","allowed_apps":[]string{"notepad"},"verify":"pid_postcondition","pipeline":[]string{"observe","understand","preflight","action","verify"}})})
	return s.middleware(mux)
}
func defaultDataDir()string{d,err:=os.UserConfigDir();if err!=nil{return filepath.Join(".",".neura")};return filepath.Join(d,"NEURA","v1")}
func main(){listen:=flag.String("listen","127.0.0.1:8765","loopback listen address");data:=flag.String("data",defaultDataDir(),"persistent data directory");workspace:=flag.String("workspace",".","allowed filesystem workspace");modelExec:=flag.String("model-exec","","optional absolute path to local model planner executable");ollamaModel:=flag.String("ollama-model","","optional local Ollama model name");ollamaURL:=flag.String("ollama-url","http://127.0.0.1:11434","loopback Ollama URL");embeddingExec:=flag.String("embedding-exec","","optional absolute path to local embedding executable");flag.Parse();if !strings.HasPrefix(*listen,"127.0.0.1:")&&!strings.HasPrefix(*listen,"[::1]:"){log.Fatal("listen address must be loopback")};recoveryMgr,err:=NewRecoveryManager(*workspace);if err!=nil{log.Fatal(err)};recoveryReport,err:=recoveryMgr.Recover();if err!=nil{log.Fatal(err)};store,err:=NewStore(*data);if err!=nil{log.Fatal(err)};tools,err:=NewToolRegistry(*workspace);if err!=nil{log.Fatal(err)};recorder,err:=NewFlightRecorder(*data);if err!=nil{log.Fatal(err)};model:=ModelAdapter{Executable:*modelExec,Timeout:20*time.Second,OllamaURL:*ollamaURL,OllamaModel:*ollamaModel};var embedding LocalEmbeddingProvider;if *embeddingExec!=""{p:=CommandEmbeddingProvider{Executable:*embeddingExec,Timeout:8*time.Second};if !p.Available(){log.Fatal("embedding executable must be an existing absolute file")};embedding=p};core:=&Core{store:store,tools:tools,model:model,embedding:embedding,recorder:recorder};tasks,err:=NewTaskRunner(core,*workspace);if err!=nil{log.Fatal(err)};if err:=tasks.store.RecoverInterrupted();err!=nil{log.Fatal(err)};improvements,err:=NewImprovementManager(*workspace);if err!=nil{log.Fatal(err)};srv:=&Server{core:core,store:store,tools:tools,model:model,allowedOrigin:"https://webinsolito.github.io",recovery:recoveryReport,tasks:tasks,improvements:improvements};httpSrv:=&http.Server{Addr:*listen,Handler:srv.routes(),ReadHeaderTimeout:5*time.Second,ReadTimeout:70*time.Second,WriteTimeout:70*time.Second,IdleTimeout:90*time.Second,MaxHeaderBytes:32*1024};fmt.Printf("NEURA V1 bridge %s listening on http://%s\n",version,*listen);log.Fatal(httpSrv.ListenAndServe())}
